-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.dim_routes DROP CONSTRAINT IF EXISTS fk_departure_station_id;

ALTER TABLE IF EXISTS public.dim_routes DROP CONSTRAINT IF EXISTS fk_destination_station_id;

ALTER TABLE IF EXISTS public.facts_departures DROP CONSTRAINT IF EXISTS fk_cargo_type_id;

ALTER TABLE IF EXISTS public.facts_departures DROP CONSTRAINT IF EXISTS fk_empty_types_id;

ALTER TABLE IF EXISTS public.facts_departures DROP CONSTRAINT IF EXISTS fk_receiver_id;

ALTER TABLE IF EXISTS public.facts_departures DROP CONSTRAINT IF EXISTS fk_route_id;

ALTER TABLE IF EXISTS public.facts_departures DROP CONSTRAINT IF EXISTS fk_sender_id;



DROP TABLE IF EXISTS public.dim_cargo_types;

CREATE TABLE IF NOT EXISTS public.dim_cargo_types
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT dim_cargo_types_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.dim_customers;

CREATE TABLE IF NOT EXISTS public.dim_customers
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT dim_customers_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.dim_empty_types;

CREATE TABLE IF NOT EXISTS public.dim_empty_types
(
    id serial NOT NULL,
    name character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT dim_empty_types_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.dim_routes;

CREATE TABLE IF NOT EXISTS public.dim_routes
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    distance numeric,
    standard_turn numeric,
    departure_down_time_rate numeric,
    arrival_delay_rate numeric,
    wagon_count_loading integer,
    train_weight_net numeric,
    train_weight_gross numeric,
    departure_station_id serial NOT NULL,
    destination_station_id serial NOT NULL,
    CONSTRAINT dim_routes_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.dim_stations;

CREATE TABLE IF NOT EXISTS public.dim_stations
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default",
    lon numeric,
    lat numeric,
    CONSTRAINT dim_stations_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.facts_departures;

CREATE TABLE IF NOT EXISTS public.facts_departures
(
    id serial NOT NULL,
    route_id integer NOT NULL,
    transportation_sheet_id integer NOT NULL,
    sender_id integer NOT NULL,
    receiver_id integer NOT NULL,
    real_wagon_loading integer NOT NULL,
    real_train_weight_gross numeric NOT NULL,
    real_train_wight_net numeric NOT NULL,
    cargo_type_id integer NOT NULL,
    empty_types_id integer NOT NULL,
    down_time numeric,
    axis_count integer NOT NULL,
    end_pending_dttm timestamp without time zone NOT NULL,
    departure_dttm timestamp without time zone,
    calendar_stamp_dttm timestamp without time zone,
    CONSTRAINT facts_departures_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.facts_givings;

CREATE TABLE IF NOT EXISTS public.facts_givings
(
    id serial NOT NULL,
    giving_dttm timestamp without time zone NOT NULL,
    enrollment_dttm timestamp without time zone NOT NULL,
    down_time_train numeric,
    facts_departures_id integer,
    transportation_sheet_id integer NOT NULL,
    interval_giving numeric,
    departure_dttm timestamp without time zone NOT NULL,
    end_pending_dttm timestamp without time zone NOT NULL,
    idle_train numeric,
    travel_time numeric,
    crew_down_time numeric,
    crew_down_time_plan numeric,
    intermediate_down_time numeric,
    CONSTRAINT facts_givings_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.dim_routes
    ADD CONSTRAINT fk_departure_station_id FOREIGN KEY (departure_station_id)
    REFERENCES public.dim_stations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dim_routes
    ADD CONSTRAINT fk_destination_station_id FOREIGN KEY (destination_station_id)
    REFERENCES public.dim_stations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.facts_departures
    ADD CONSTRAINT fk_cargo_type_id FOREIGN KEY (cargo_type_id)
    REFERENCES public.dim_cargo_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.facts_departures
    ADD CONSTRAINT fk_empty_types_id FOREIGN KEY (empty_types_id)
    REFERENCES public.dim_empty_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.facts_departures
    ADD CONSTRAINT fk_receiver_id FOREIGN KEY (receiver_id)
    REFERENCES public.dim_customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.facts_departures
    ADD CONSTRAINT fk_route_id FOREIGN KEY (route_id)
    REFERENCES public.dim_routes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.facts_departures
    ADD CONSTRAINT fk_sender_id FOREIGN KEY (sender_id)
    REFERENCES public.dim_customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;